### ISSUE TITLE
API CORS 문제

### ISSUE THREAD

**Issue by yhuj79** [Nomad-Link/Nomad-Link#28]
<img width="396" alt="1" src="https://user-images.githubusercontent.com/96750543/185768546-ba6ded50-afdb-4242-96dd-d49c0e711e76.png">
<img width="495" alt="2" src="https://user-images.githubusercontent.com/96750543/185768596-802c2bea-2a2c-4cf7-8776-3dbb49c88627.png">

서비스에는 이상이 없는데 form 전송 과정에서
safari, chrome 경고 출력되는중

**Comment by rngustj9139** [comment]
![image](https://user-images.githubusercontent.com/43543906/185916605-5680d7c3-5bbe-4c26-9df5-714944d5c1e7.png)

http://localhost:8080/enterprise/recruit/form 에서 데이터 POST로 전송후 http://localhost:8080/enterprise/recruit/complete로
자동으로 라우트 되는 과정에서 콘솔 에러 발생

But DB에 데이터 Load는 정상적

**Comment by yhuj79** [comment]
Failed to load resource: the server responded with a status of 500 (Internal Server Error)
